import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "./globals.css";


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 bg-white/80 backdrop-blur border-b">
          <div className="p-4 flex items-center justify-between max-w-5xl mx-auto">
            <a href="/" className="font-semibold">
              Socrates Zayas
            </a>
            <nav className="space-x-4">
              <a className="underline" href="/projects">Projects</a>
              <a className="underline" href="/resume">Resume</a>
			  <a className="underline" href="/security">Security</a>
              <a
                className="underline"
                href="https://github.com/imdocsoc"
                target="_blank"
                rel="noreferrer"
              >
                GitHub
              </a>
            </nav>
          </div>
        </header>

        <div className="max-w-5xl mx-auto p-6">
          {children}
        </div>
      </body>
    </html>
  );
}




